[versions]

kotlin = "2.2.10"
kotlinx = "1.10.2"
kotlinx_json = "1.9.0"
ktor = "3.3.0"
koog = "0.6.2"
slf4j = "2.0.17"

[libraries]

# Kotlin BOM
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Kotlinx
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx_json" }

#Ktor
ktor-bom = {module = "io.ktor:ktor-bom", version.ref = "ktor"}
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json"}

# ktor-client
ktor-client-core = { module = "io.ktor:ktor-client-core"}
ktor-client-cio = { module = "io.ktor:ktor-client-cio"}
ktor-client-content = { module = "io.ktor:ktor-client-content-negotiation"}
ktor-client-logging = { module = "io.ktor:ktor-client-logging"}

# ktor-server
ktor-server-core = { module = "io.ktor:ktor-server-core"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty"}
ktor-server-content = { module = "io.ktor:ktor-server-content-negotiation"}
ktor-server-cors = { module = "io.ktor:ktor-server-cors"}
ktor-server-call = { module = "io.ktor:ktor-server-call-logging"}
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions"}
ktor-server-status-pages = {module = "io.ktor:ktor-server-status-pages"}



# Koog
koog-agents = { module = "ai.koog:koog-agents", version.ref = "koog" }

#  Simple Logging Facade for Java
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
